---
- name: Bagisto Application Deployment
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Pull image
      community.docker.docker_image_pull:
        name: webkul/bagisto
        tag: 2.3.6

    - name: Start container
      community.docker.docker_container:
        cleanup: true
        command: bagisto --version
        detach: false
        image: webkul/bagisto:2.3.6
        name: bagisto-container
        output_logs: true

    - name: Show output
      ansible.builtin.debug:
        msg: "{{ output.container.Output }}"